version: '3.3'

services:
  db:
    image: mysql
    volumes:
      - employeeInfodb_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: eric
      MYSQL_PASSWORD: admin
volumes:
  employeeInfodb_data: {}